---
- name: Add Docker GPG apt Key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Update apt and install Docker
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Module for Python
  pip:
    name: docker
