- name: Pull Kenkins Docker image
  docker_image:
    name: "{{ jenkins_image }}"
    source: pull

- name: Create a volume 
  docker_volume:
    name: "{{ jenkins_volume }}"
    state: present

- name: Deploy container
  docker_container:
    name: "{{ jenkins_container_name }}"
    image: "{{ jenkins_image }}"
    volumes:
      - "{{ jenkins_volume }}:/var/jenkins_home"
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
